language: en

pipeline:
- name: dim_regex.DimRegexPreprocessor
- name: dim_ner.DimNerPreprocessor
- name: SpacyNLP
- name: SpacyTokenizer
- name: RegexFeaturizer
- name: SpacyFeaturizer
- name: CRFEntityExtractor
- name: EntitySynonymMapper
- name: SklearnIntentClassifier
- name: custom_intent_classifier.ImageDroppedCheck
- name: custom_intent_classifier.SingleNumberCheck

policies:
- batch_size: 50
  epochs: 200
  max_training_samples: 300
  name: KerasPolicy
- fallback_action_name: action_default_fallback
  name: FallbackPolicy
- max_history: 5
  name: MemoizationPolicy
- name: FormPolicy
- name: MappingPolicy
